{{- if .Values.otel.createInstrumentation }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: auto-instrumentation
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
spec:
  exporter:
    endpoint: {{ .Values.otel.endpoint | quote }}
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.3.0
{{- end }}
