name: azure-microservices-demo
description: Azure microservices demo platform — 4-stage IaC
runtime:
  name: nodejs
  options:
    typescript: true
main: stage1.ts   # change to stage2.ts / stage3.ts / stage4.ts to deploy other stages
config:
  location:
    default: uksouth
  env:
    default: demo
