{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
  annotations:
    # AKS Workload Identity — links this SA to the Azure Managed Identity
    # so pods can authenticate to Key Vault, Service Bus, etc. without secrets.
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentityClientId | quote }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
