apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "${{ values.serviceName }}.fullname" . }}-kv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "${{ values.serviceName }}.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Chart.Name }}-secrets
      type: Opaque
      data:
        - objectName: servicebus-connection-string
          key: ServiceBus--ConnectionString
        {{- if .Values.cosmos }}
        - objectName: cosmos-{{ .Chart.Name }}-connection-string
          key: CosmosDb--ConnectionString
        {{- end }}
        {{- if .Values.sql }}
        - objectName: sql-{{ .Chart.Name }}-connection-string
          key: Sql--ConnectionString
        {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.workloadIdentityClientId | quote }}
    keyvaultName: {{ .Values.global.keyVaultName | default "kv-stage2-demo" | quote }}
    tenantId: {{ .Values.global.tenantId | default "" | quote }}
    objects: |
      array:
        - |
          objectName: servicebus-connection-string
          objectType: secret
        {{- if .Values.cosmos }}
        - |
          objectName: cosmos-{{ .Chart.Name }}-connection-string
          objectType: secret
        {{- end }}
        {{- if .Values.sql }}
        - |
          objectName: sql-{{ .Chart.Name }}-connection-string
          objectType: secret
        {{- end }}
